<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHgurzf8\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHgurzf8/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerHgurzf8.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerHgurzf8\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerHgurzf8\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Hgurzf8',
    'container.build_id' => 'a5efc6d0',
    'container.build_time' => 1535022767,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerHgurzf8');
