<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP2tbbia\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP2tbbia/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerP2tbbia.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerP2tbbia\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerP2tbbia\appDevDebugProjectContainer(array(
    'container.build_hash' => 'P2tbbia',
    'container.build_id' => 'e93b222c',
    'container.build_time' => 1532946918,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerP2tbbia');
